# 大模型模型配置文件

OPENAI_MODEL_NAME : 
  "gpt-oss:120b"
OPENAI_BASE_URL : 
  "http://10.11.150.143:11434/v1"
OPENAI_API_KEY : 
  "laob"


# OPENAI_MODEL_NAME : 
#   "qwen-max"
# OPENAI_BASE_URL : 
#   "https://dashscope.aliyuncs.com/compatible-mode/v1"
# OPENAI_API_KEY : 
#   "sk-e5d2bc1f146e44ebbf274905cea0f7da"




EMBEDDING_MODEL :
  "mxbai-embed-large:latest"
EMBEDDING_URL : 
  "http://10.11.150.143:11434"

